# Generated by Django 3.2.9 on 2021-12-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211206_2044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryProduct',
            new_name='ProductCategory',
        ),
    ]
